CI/CD update

diff --git a/.github/workflows/deploy.yaml b/.github/workflows/deploy.yaml
--- a/.github/workflows/deploy.yaml
+++ b/.github/workflows/deploy.yaml
@@ -39,10 +39,45 @@ jobs:
           username: ${{ secrets.DO_USER }}
           key: ${{ secrets.DO_SSH_KEY }}
           script: |
+            set -e
+
+            IMAGE=ghcr.io/nazarkurii/marshrutka_customer_ui:latest
+            OLD_CONTAINER=customer_ui
+            NEW_CONTAINER=customer_ui_latest
+            NETWORK=marshrutka_net
+
             cd ~/marshrutka/deployment
             git pull origin main
-            docker rmi ghcr.io/nazarkurii/marshrutka_customer_ui:latest
-            docker compose pull
-            docker compose up -d 
-            docker image prune -f
-            docker container prune -f
+
+            if ! docker network inspect $NETWORK >/dev/null 2>&1; then
+              docker network create $NETWORK
+            fi
+
+            docker pull $IMAGE
+            docker run -d \
+              --network $NETWORK \
+              --name $NEW_CONTAINER
+
+            COUNT=0
+            MAX_TRIES=10
+
+            until [ "(docker inspect --format='{{State.Health.Status}}') $NEW_CONTAINER" = "healty" ]; do
+              COUNT=$((COUNT+1))
+
+              if [ $COUNT -ge $MAX_TRIES ]; then
+                echo "Health check failed"
+              fi
+
+              sleep 1
+            done
+
+            docker network disconnect $NETWORK $OLD_CONTAINER || true
+            docker stop $OLD_CONTAINER || true
+            docker rm $OLD_CONTAINER || true
+
+            docker rename $NEW_CONTAINER $OLD_CONTAINER
+
+            docker restart nginx
+
+            docker container prune -a -f
+            docker image prune -a -f
