CI/CD update

diff --git a/.github/workflows/deploy.yaml b/.github/workflows/deploy.yaml
--- a/.github/workflows/deploy.yaml
+++ b/.github/workflows/deploy.yaml
@@ -39,10 +39,60 @@ jobs:
           username: ${{ secrets.DO_USER }}
           key: ${{ secrets.DO_SSH_KEY }}
           script: |
+            set -e
+
+            IMAGE=ghcr.io/nazarkurii/marshrutka_customer_ui:latest
+            OLD_CONTAINER=customer_ui
+            NEW_CONTAINER=customer_ui_latest
+            NETWORK=marshrutka_net
+
             cd ~/marshrutka/deployment
-            git pull origin main
-            docker rmi ghcr.io/nazarkurii/marshrutka_customer_ui:latest
-            docker compose pull
-            docker compose up -d 
-            docker image prune -f
+            git pull origin main || true
+
+            if ! docker network inspect $NETWORK >/dev/null 2>&1; then
+              docker network create $NETWORK
+            fi
+
+            docker pull $IMAGE
+            docker run -d \
+              --network $NETWORK \
+              --name $NEW_CONTAINER \
+              $IMAGE
+
+            COUNT=0
+            MAX_TRIES=10
+
+
+            while true; do
+              STATUS=$(docker inspect --format='{{.State.Health.Status}}' $NEW_CONTAINER 2>/dev/null || echo "starting")
+
+              if [ "$STATUS" = "healthy" ]; then
+                break
+              fi
+
+              COUNT=$((COUNT+1))
+
+              echo "Status:"
+              echo $STATUS
+
+              if [ "$COUNT" -ge "$MAX_TRIES" ]; then
+                echo "Health check failed"
+                docker logs $NEW_CONTAINER || true
+                docker rm -f $NEW_CONTAINER || true
+                docker image prune -f -a || true
+                exit 1
+              fi
+
+              sleep 3
+            done
+
+            docker network disconnect $NETWORK $OLD_CONTAINER || true
+            docker stop $OLD_CONTAINER || true
+            docker rm $OLD_CONTAINER || true
+
+            docker rename $NEW_CONTAINER $OLD_CONTAINER
+
+            docker restart nginx
+
             docker container prune -f
+            docker image prune -a -f
